Pro 3070
kiva/Mikoba pull request #60
Opened 2021-06-01 20:28 UTC by michelleinez

2021-06-01 21:10 UTC, horationunez requested changes

2021-06-01 21:10 UTC, horationunez commented on mikoba/ViewModels/SSI/SSICredentialViewModel.cs
> +            DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0);
nit: you could use `var` here

2021-06-02 21:31 UTC, michelleinez commented on mikoba/ViewModels/SSI/SSICredentialViewModel.cs
> +            DateTime dtDateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0);
done

2021-06-02 21:44 UTC, horationunez approved these changes

2021-06-03 15:41 UTC, merged